- name: Copy Redis systemd service file
  template:
    src: ../templates/redis.service.j2
    dest: /etc/systemd/system/quay-redis.service

- name: Check if Redis image is loaded
  command: podman inspect --type=image {{ redis_image }}
  register: redis_image

- name: Pull Redis image
  containers.podman.podman_image:
    name: "{{ redis_image }}"
  when: redis_image is not defined

- name: Start Redis service
  systemd:
    name: quay-redis.service
    enabled: yes
    daemon_reload: yes
    state: started
